activity = ["Sleeping", "Fighting", "Preparing an Ambush",
    "sharpening rusty weapons",
    "gambling with bones and coins",
    "brewing foul potions over a flickering fire",
    "interrogating a captive adventurer",
    "chanting in a dark ritual circle",
    "feasting on cave fungus and rat meat",
    "scrawling runes on dungeon walls",
    "patrolling ancient stone hallways",
    "sleeping in a pile of stolen loot",
    "arguing over loot distribution",
    "tending to wounded allies",
    "training with crude weapons",
    "summoning a minor demon",
    "whispering to ancient spirits",
    "repairing a broken trap",
    "digging a new tunnel passage",
    "conducting necrotic experiments",
    "meditating before a cursed relic",
    "fighting amongst themselves",
    "practicing magic in secret alcoves",
    "scouting upper levels in disguise",
    "collecting venom from dungeon spiders",
    "writing grim poetry in blood",
    "constructing effigies to dark gods",
    "guarding a sealed vault door",]